# Generated by Django 2.1.5 on 2019-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Shere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
